// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-mddUZ6JWCQUtgt-E0u_i1Ri8SfJBKAg',
    appId: '1:223302796269:web:c87f5b5ec83fda547c1de4',
    messagingSenderId: '223302796269',
    projectId: 'senoa-ae0e3',
    authDomain: 'senoa-ae0e3.firebaseapp.com',
    storageBucket: 'senoa-ae0e3.firebasestorage.app',
    measurementId: 'G-5DLD1ESZFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE-MNjbhj62QwSaBxz5jmg3s20PevpMFQ',
    appId: '1:223302796269:android:fc2d9643c03a43a57c1de4',
    messagingSenderId: '223302796269',
    projectId: 'senoa-ae0e3',
    storageBucket: 'senoa-ae0e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWoZLkM0vDL5JvK30cu9iGpTfim2h9oo8',
    appId: '1:223302796269:ios:1da172adac03199b7c1de4',
    messagingSenderId: '223302796269',
    projectId: 'senoa-ae0e3',
    storageBucket: 'senoa-ae0e3.firebasestorage.app',
    iosBundleId: 'com.example.senoa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWoZLkM0vDL5JvK30cu9iGpTfim2h9oo8',
    appId: '1:223302796269:ios:1da172adac03199b7c1de4',
    messagingSenderId: '223302796269',
    projectId: 'senoa-ae0e3',
    storageBucket: 'senoa-ae0e3.firebasestorage.app',
    iosBundleId: 'com.example.senoa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-mddUZ6JWCQUtgt-E0u_i1Ri8SfJBKAg',
    appId: '1:223302796269:web:0c27f76d00f8322c7c1de4',
    messagingSenderId: '223302796269',
    projectId: 'senoa-ae0e3',
    authDomain: 'senoa-ae0e3.firebaseapp.com',
    storageBucket: 'senoa-ae0e3.firebasestorage.app',
    measurementId: 'G-PGZZ1ZXMDQ',
  );
}
